/* @generated by tools/make-palette.mjs — do not hand-edit; run --write */

/** Theme tokens, mirrored so JS (canvas previews, icon/OG generation, the palette
 *  audit) can never disagree with what CSS paints. */
export const TOKENS = {
  dark: {
    "--bg": "#0b0e12",
    "--bg-2": "#0f141a",
    "--panel": "#141a22",
    "--panel-2": "#1a222c",
    "--line": "#243039",
    "--line-2": "#31414c",
    "--fg": "#e7edf2",
    "--fg-2": "#a2b2bd",
    "--fg-3": "#6d7f8b",
    "--accent": "#40d9c1",
    "--on-accent": "#1f0e13",
    "--tool-dark": "#40d9c1",
    "--tool-on-dark": "#1f0e13",
    "--accent-2": "#ed9ee5",
    "--ok": "#63d18f",
    "--warn": "#f0ba59",
    "--err": "#f75d59",
  },
  light: {
    "--bg": "#f2f4f4",
    "--bg-2": "#e9ecec",
    "--panel": "#ffffff",
    "--panel-2": "#f7f9f8",
    "--line": "#d9dedd",
    "--line-2": "#c1c9c8",
    "--fg": "#101619",
    "--fg-2": "#4b5a63",
    "--fg-3": "#78868f",
    "--accent": "#007a6b",
    "--on-accent": "#ffffff",
    "--tool-light": "#007a6b",
    "--tool-on-light": "#ffffff",
    "--accent-2": "#93488d",
    "--ok": "#0b7643",
    "--warn": "#8a5601",
    "--err": "#ba1e20",
  },
};

/** Per-tool accent pairs, derived from evenly spaced OKLCH hues. */
export const TOOL_ACCENTS = {
  time: {"dark":"#ff9ea6","light":"#a8424f","onDark":"#1f0e13","onLight":"#ffffff","hue":15},
  images: {"dark":"#ffa47a","light":"#a64a18","onDark":"#1f0e13","onLight":"#ffffff","hue":45},
  gradient: {"dark":"#eeb154","light":"#8d5e00","onDark":"#1f0e13","onLight":"#ffffff","hue":75},
  regex: {"dark":"#cac256","light":"#736c02","onDark":"#1f0e13","onLight":"#ffffff","hue":105},
  scale: {"dark":"#99d079","light":"#44791c","onDark":"#1f0e13","onLight":"#ffffff","hue":135},
  text: {"dark":"#5ed8a9","light":"#007c59","onDark":"#1f0e13","onLight":"#ffffff","hue":165},
  csv: {"dark":"#2ad7d7","light":"#057879","onDark":"#1f0e13","onLight":"#ffffff","hue":195},
  json: {"dark":"#49cffc","light":"#037493","onDark":"#1f0e13","onLight":"#ffffff","hue":225},
  shadow: {"dark":"#91c1ff","light":"#2a69b4","onDark":"#1f0e13","onLight":"#ffffff","hue":255},
  hash: {"dark":"#b6b4fe","light":"#635ab2","onDark":"#1f0e13","onLight":"#ffffff","hue":285},
  theme: {"dark":"#dda4f7","light":"#864d9d","onDark":"#1f0e13","onLight":"#ffffff","hue":315},
  color: {"dark":"#f99bd1","light":"#9d447a","onDark":"#1f0e13","onLight":"#ffffff","hue":345},
};

export const accentFor = (id, theme) => TOOL_ACCENTS[id]?.[theme === "light" ? "light" : "dark"];
export const onFor = (id, theme) => TOOL_ACCENTS[id]?.[theme === "light" ? "onLight" : "onDark"];
